const path=require('path')
const exp=require('express')
const bodyparser=require('body-parser')
const adminfile=require('./routers/admin1')
const shopfile=require('./routers/shop1')
const contactfile=require('./routers/contact')
let rou=exp()
rou.use(bodyparser.urlencoded({extended :true}))
rou.use(exp.static(path.join(__dirname,'public')))
rou.use(adminfile)
rou.use(shopfile)
rou.use(contactfile)
rou.use((req,res,next)=>res.status(404).sendFile(path.join(__dirname,'views','404.html'))) 

rou.listen(3000)    