const exp=require('express')
let rou=exp()
const adminfile=require('./routers/admin')
const shopfile=require('./routers/shop')
const bodyparser=require('body-parser')
rou.use(bodyparser.urlencoded({extended :true}))
rou.use(adminfile)
rou.use(shopfile)
rou.use((req,res,next)=>res.status(404).send('<div>page not found</div>'))
rou.listen(3000)